services:
  - type: web
    name: ugc-ai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install --no-cache-dir --only-binary=all -r requirements.txt && python startup.py
    startCommand: cd backend && python render-startup.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: PIP_NO_COMPILE
        value: "1"